# Generated by Django 3.2 on 2023-07-21 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.', 'validators': 'invalid'}, help_text='Required. 32 characters or fewer. Letters, digits and . _ only.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9][a-zA-Z0-9_\\.]+$', 'Enter a valid username starting with a-z.')], verbose_name='username'),
        ),
    ]
