# Generated by Django 3.2 on 2023-07-22 13:18

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListOfCode', django_mysql.models.ListCharField(models.CharField(max_length=7, verbose_name='code'), max_length=130, size=15)),
                ('ListOfCount', django_mysql.models.ListCharField(models.CharField(max_length=4, verbose_name='count'), max_length=90, size=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.user')),
            ],
        ),
    ]
