# Generated by Django 3.2 on 2023-08-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ListOfCode',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='ListOfCount',
            new_name='Count',
        ),
    ]
