# Generated by Django 3.2 on 2023-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Count',
            field=models.SmallIntegerField(),
        ),
    ]
