# Generated by Django 3.2 on 2023-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='consumed_code',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='consumed refrence code'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'void'), (10, 'paid'), (20, 'error'), (30, 'canceled'), (31, 'refunded')], default=0, verbose_name='status'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Carts',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
