# Generated by Django 3.2 on 2023-08-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230813_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
