# Generated by Django 3.2 on 2023-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.', 'validators': 'invalid'}, help_text='Required. 32 characters or fewer. Letters, digits and . _ only.', max_length=32, unique=True, verbose_name='username'),
        ),
    ]
