# Generated by Django 4.2.4 on 2023-08-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Count',
            field=models.PositiveIntegerField(),
        ),
    ]
