# Generated by Django 4.2.4 on 2023-10-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
