# Generated by Django 4.2.4 on 2023-10-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updade time'),
        ),
    ]
