# Generated by Django 4.2.4 on 2023-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=512, verbose_name='Address')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('description', models.TextField(verbose_name='description')),
                ('code', models.IntegerField(default=1, verbose_name='code')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='updade time')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
                'db_table': 'Abouts',
            },
        ),
    ]
