# Generated by Django 4.2.4 on 2023-10-03 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCodes', django_mysql.models.ListCharField(models.CharField(max_length=7, verbose_name='code'), max_length=130, size=15)),
                ('ProductCounts', django_mysql.models.ListCharField(models.CharField(max_length=4, verbose_name='count'), max_length=90, size=15)),
                ('Price', models.BigIntegerField()),
                ('Address', models.TextField()),
                ('status_pay', models.PositiveSmallIntegerField(choices=[(0, 'void'), (10, 'paid'), (20, 'error'), (30, 'canceled'), (31, 'refunded')], default=0, verbose_name='pay status')),
                ('status_build', models.PositiveSmallIntegerField(choices=[(0, 'RECORD'), (10, 'CONSTRUCTING'), (20, 'MADE'), (30, 'TRANSPORTATION'), (31, 'CANCEL')], default=0, verbose_name='build status')),
                ('consumed_code', models.PositiveIntegerField(db_index=True, null=True, verbose_name='consumed refrence code')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Orders',
            },
        ),
    ]
