# Generated by Django 3.2 on 2023-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230813_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status_build',
            field=models.PositiveSmallIntegerField(choices=[(0, 'RECORD'), (10, 'CONSTRUCTING'), (20, 'MADE'), (30, 'TRANSPORTATION'), (31, 'CANCEL')], default=0, verbose_name='build status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_pay',
            field=models.PositiveSmallIntegerField(choices=[(0, 'void'), (10, 'paid'), (20, 'error'), (30, 'canceled'), (31, 'refunded')], default=0, verbose_name='pay status'),
        ),
    ]
