# Generated by Django 4.2.4 on 2023-10-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='categories/%Y/%m/%d/', verbose_name='avatar'),
        ),
    ]
